## Template for the root compose.yml generated by dcm init

write_compose_yml() {
  cat >compose.yml <<'EOF'
# Main Docker Compose file — generated by dcm init
services:
  bootstrap:
    image: alpine:latest
    command: >
      sh -c "
        echo 'Verifying environment configuration...';
        echo '';
        if [ ! -f '/config/config.env' ]; then
          echo 'ERROR: config.env not found at ${DCM_CONFIG_DIR}/config.env';
          echo 'Please run: dcm service config';
          exit 1;
        fi;
        echo 'config.env found. All checks passed.';
        exit 0;
      "
    environment:
      REQUIRED_CHECK: ${DCM_ROOT?} ${DCM_CONFIG_DIR?} ${DCM_VOLUMES_DIR?}
    volumes:
      - ${DCM_CONFIG_DIR}:/config:ro,z

include:
  - .dcm/services/compose/services.yml

networks:
  db:
    driver: bridge
  web:
    driver: bridge
EOF
}
