## Add any function here that is needed in more than one parts of your
## application, or that you otherwise wish to extract from the main function
## scripts.
##
## Note that code here should be wrapped inside bash functions, and it is
## recommended to have a separate file for each function.
##
## Sub-directories will also be scanned for *.sh, so you have no reason not
## to organize your code neatly.
to_pascal_case() {
  local input="$1"

  # Normalizza separatori
  input=$(echo "$input" | sed -E 's/[-_]+/ /g')

  # Split camelCase
  input=$(echo "$input" | sed -E 's/([a-z0-9])([A-Z])/\1 \2/g')

  # Capitalizza ogni parola e unisce
  echo "$input" | awk '{
        for (i = 1; i <= NF; i++) {
            $i = toupper(substr($i,1,1)) substr($i,2)
        }
        printf "%s\n", $0
    }' | tr -d ' '
}

# Regenerate config.env from all partial files in .dcm/services/config/<repo>/<service>/config.partial
regenerate_config_env() {
  local config_env="$DCM_CONFIG_DIR/config.env"

  # Load environment variables if not already loaded
  if [ -z "$DCM_ROOT" ]; then
    load_env
    if [ -z "$DCM_ROOT" ]; then
      echo "Error: DCM_ROOT not set and .env not found"
      return 1
    fi
  fi

  # Create header for config.env
  cat > "$config_env" << 'EOF'
# Docker Collection Manager Configuration
# Generated by dcm service config
# DO NOT EDIT THIS FILE MANUALLY - regenerate using: dcm service config

EOF

  # Append all partial files (sorted for consistent order)
  local partial_count=0
  for partial_file in $(find "$DCM_CONFIG_DIR" -type f -name "config.partial" 2>/dev/null | sort); do
    if [ -f "$partial_file" ]; then
      cat "$partial_file" >> "$config_env"
      partial_count=$((partial_count + 1))
    fi
  done

  if [ $partial_count -eq 0 ]; then
    echo "✓ Configuration file created (empty): $config_env"
  else
    echo "✓ Configuration file regenerated from $partial_count partial file(s): $config_env"
  fi

  return 0
}
