## Hosts management helpers
## Generates state/services/compose/hosts.yml with extra_hosts for all containers

# Regenerate hosts.yml from Caddyfile.Services and enabled containers.
# Call after service enable/disable or whenever the domain list changes.
hosts_sync() {
  local caddyfile_services="$DCM_CONFIG_DIR/$DCM_PROXY_SERVICE/Caddyfile.Services"

  # Load config.env to get CADDY_MAIN_DOMAIN and other user-defined variables
  local config_env="$DCM_CONFIG_DIR/config.env"
  if [ -f "$config_env" ]; then
    set -a; source "$config_env"; set +a
  fi

  # Extract unique domains from Caddyfile.Services
  local domains=()
  if [ -f "$caddyfile_services" ] && [ -n "$CADDY_MAIN_DOMAIN" ]; then
    while IFS= read -r domain; do
      [ -n "$domain" ] && domains+=("$domain")
    done < <(grep -oE '^[a-zA-Z0-9._-]+\.\{\$CADDY_MAIN_DOMAIN\}' "$caddyfile_services" \
             | sed "s/{\$CADDY_MAIN_DOMAIN}/$CADDY_MAIN_DOMAIN/" \
             | sort -u)
  fi

  # Get all enabled containers
  local all_containers=()
  while IFS= read -r service; do
    [ -n "$service" ] || continue
    while IFS= read -r container; do
      [ -n "$container" ] && all_containers+=("$container")
    done < <(service_config_get_containers "$service")
  done < <(service_config_get_all_enabled)

  # Generate hosts.yml — empty if no domains or no containers
  if [ ${#all_containers[@]} -eq 0 ] || [ ${#domains[@]} -eq 0 ]; then
    echo "services: {}" > "$DCM_HOSTS_FILE"
    return 0
  fi

  {
    echo "# hosts.yml — generated by dcm service sync-hosts"
    echo "# DO NOT EDIT MANUALLY — regenerated on service enable/disable"
    echo "services:"
    for container in "${all_containers[@]}"; do
      echo "  $container:"
      echo "    extra_hosts:"
      for domain in "${domains[@]}"; do
        echo "      - \"$domain:host-gateway\""
      done
    done
  } > "$DCM_HOSTS_FILE"
}
