# Network configuration
DEFAULT_CADDY_MAIN_DOMAIN=apug.it
printf '%b\n' "--- Network Configuration ---"
read -p "CADDY_MAIN_DOMAIN [$DEFAULT_CADDY_MAIN_DOMAIN]: " caddy_domain
caddy_domain=${caddy_domain:-$DEFAULT_CADDY_MAIN_DOMAIN}
printf '%b\n' "" >&2

# Create Caddyfile.Before, Caddyfile.Services, Caddyfile.After if not exists
caddy_config_dir="$DCM_CONFIG_DIR/_dcm/Caddy"
mkdir -p "$caddy_config_dir"

if [ ! -f "$caddy_config_dir/Caddyfile.Before" ]; then
  cat > "$caddy_config_dir/Caddyfile.Before" <<'CEOF'
# Caddyfile.Before - Custom Caddy configuration loaded BEFORE service blocks.
# Add global options, reusable snippets, or any config that must precede services.
# This file is managed manually.
CEOF
  printf '%b\n' "✓ Caddyfile.Before created"
fi

if [ ! -f "$caddy_config_dir/Caddyfile.Services" ]; then
  cat > "$caddy_config_dir/Caddyfile.Services" <<'CEOF'
# Caddyfile.Services - Auto-generated by dcm service enable/disable.
# DO NOT EDIT THIS FILE MANUALLY - it is regenerated automatically.
# Each service block is delimited by # BEGIN and # END markers.
CEOF
  printf '%b\n' "✓ Caddyfile.Services created"
fi

if [ ! -f "$caddy_config_dir/Caddyfile.After" ]; then
  cat > "$caddy_config_dir/Caddyfile.After" <<'CEOF'
# Caddyfile.After - Custom Caddy configuration loaded AFTER service blocks.
# Add catch-all routes, global redirects, or any config that must follow services.
# This file is managed manually.
CEOF
  printf '%b\n' "✓ Caddyfile.After created"
fi

if [ ! -f "$SERVICE_CONFIG_DIR/volumes.yml" ]; then
  cat > "$SERVICE_CONFIG_DIR/volumes.yml" <<'EOF'
# Caddy User-defined Volumes
#
# Aggiungi qui i volumi da montare nel container caddy.
# Utile per servire file statici (CSS, JS, immagini) delle tue applicazioni.
#
# Il path host deve corrispondere a quello montato nei container PHP
# in modo che Caddy e PHP vedano gli stessi file.
#
# Esempio (DcmPhp apps):
#
# services:
#   caddy:
#     volumes:
#       - ${DCM_VOLUMES_DIR}/DcmPhp/apps:/var/www/html:z
#
# Dopo ogni modifica: docker compose up -d --force-recreate caddy

services:
  caddy:
    volumes: []
EOF
  printf '%b\n' "✓ volumes.yml creato in $SERVICE_CONFIG_DIR" >&2
fi

# Write partial config file directly to the service config directory
# REPO_NAME, SERVICE_NAME, and SERVICE_CONFIG_DIR are provided by dcm service config
cat >"$SERVICE_CONFIG_DIR/config.partial" <<EOF

# Network Configuration
CADDY_MAIN_DOMAIN=$caddy_domain
EOF
